import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { Logger } from '../logging/logger';

export interface WebviewInitData {
  [key: string]: unknown;
}

export interface WebviewHostOptions {
  viewType: string;
  title: string;
  bundleId: string; // matches the webviews/src/<bundleId>/ directory
  initData?: WebviewInitData;
  viewColumn?: vscode.ViewColumn;
  retainContextWhenHidden?: boolean;
  iconPath?: vscode.Uri | { light: vscode.Uri; dark: vscode.Uri };
}

export class WebviewHost {
  readonly panel: vscode.WebviewPanel;
  private readonly _onMessage = new vscode.EventEmitter<any>();
  readonly onMessage = this._onMessage.event;
  private readonly _onDispose = new vscode.EventEmitter<void>();
  readonly onDispose = this._onDispose.event;
  private disposed = false;

  constructor(
    private readonly ctx: vscode.ExtensionContext,
    private readonly opts: WebviewHostOptions
  ) {
    this.panel = vscode.window.createWebviewPanel(
      opts.viewType,
      opts.title,
      opts.viewColumn ?? vscode.ViewColumn.Active,
      {
        enableScripts: true,
        retainContextWhenHidden: opts.retainContextWhenHidden ?? true,
        localResourceRoots: [vscode.Uri.joinPath(ctx.extensionUri, 'webviews', 'dist')]
      }
    );
    if (opts.iconPath) {
      this.panel.iconPath = opts.iconPath;
    }
    this.panel.webview.html = this.buildHtml();
    this.panel.webview.onDidReceiveMessage((msg: any) => {
      if (msg?.command === 'webviewReady' && opts.initData) {
        Logger.info(`[WebviewHost] webviewReady received for ${opts.viewType}, sending init`);
        this.post({ command: 'init', data: opts.initData });
      } else {
        this._onMessage.fire(msg);
      }
    });
    this.panel.onDidDispose(() => {
      if (this.disposed) return;
      this.disposed = true;
      this._onDispose.fire();
    });
  }

  post(msg: any): void {
    if (this.disposed) return;
    void this.panel.webview.postMessage(msg);
  }

  reveal(): void {
    this.panel.reveal();
  }

  dispose(): void {
    this.panel.dispose();
  }

  private buildHtml(): string {
    const distRoot = vscode.Uri.joinPath(this.ctx.extensionUri, 'webviews', 'dist');
    // Vite emits HTML at dist/src/<bundleId>/index.html; fallback to dist/<bundleId>/index.html
    const candidates = [
      path.join(distRoot.fsPath, 'src', this.opts.bundleId, 'index.html'),
      path.join(distRoot.fsPath, this.opts.bundleId, 'index.html')
    ];
    let html: string | undefined;
    let indexPath = '';
    for (const p of candidates) {
      try {
        html = fs.readFileSync(p, 'utf8');
        indexPath = p;
        break;
      } catch { /* try next */ }
    }
    if (!html) {
      Logger.error(`Webview bundle missing: ${candidates.join(', ')}`);
      return this.fallbackHtml(`Webview bundle '${this.opts.bundleId}' not built. Run "npm run build:webviews".`);
    }

    const distUri = this.panel.webview.asWebviewUri(distRoot).toString();

    // Replace asset references generated by Vite. Patterns:
    //   /<bundleId>/assets/...  /shared/...  /<PascalCase>/assets/...
    html = html.replace(/(?:src|href)="\/?([^"]+)"/g, (m, p1) => {
      // Convert bundle-relative or absolute asset paths
      if (p1.startsWith('http')) return m;
      const cleaned = p1.replace(/^\.\//, '');
      return m.replace(`"${p1}"`, `"${distUri}/${cleaned}"`).replace(`"/${cleaned}"`, `"${distUri}/${cleaned}"`);
    });

    // CSP nonce (basic)
    const nonce = Date.now().toString(36) + Math.random().toString(36).slice(2);
    const csp = [
      `default-src 'none';`,
      `img-src ${this.panel.webview.cspSource} https: data:;`,
      `style-src ${this.panel.webview.cspSource} 'unsafe-inline';`,
      `font-src ${this.panel.webview.cspSource};`,
      `script-src ${this.panel.webview.cspSource} 'nonce-${nonce}';`,
      `worker-src blob: ${this.panel.webview.cspSource};`,
      `connect-src ${this.panel.webview.cspSource};`
    ].join(' ');

    if (!/Content-Security-Policy/.test(html)) {
      html = html.replace('<head>', `<head>\n<meta http-equiv="Content-Security-Policy" content="${csp}">`);
    }
    // Add nonce to all scripts
    html = html.replace(/<script /g, `<script nonce="${nonce}" `);
    return html;
  }

  private fallbackHtml(message: string): string {
    return `<!doctype html><html><body style="font-family:sans-serif;padding:20px;color:var(--vscode-foreground);">
      <h2>${this.opts.title}</h2>
      <p>${message}</p>
    </body></html>`;
  }
}
